name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev # Change this to your desired branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          cd functions
          npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Set environment variables
        run: |
          cd functions
          touch .env
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Authenticate with Firebase
        run: firebase deploy --only functions,hosting --token ${{ secrets.FIREBASE_TOKEN }}